export default [
  {
    name: 'Canada',
    activeArmedForces: 67000,
    region: 'North America',
    code: 'ca',
  },
  {
    name: 'USA',
    activeArmedForces: 1388000,
    region: 'North America',
    code: 'us',
  },
  {
    name: 'Albania',
    activeArmedForces: 8000,
    region: 'Europe',
    code: 'al',
  },
  {
    name: 'Austria',
    activeArmedForces: 22000,
    region: 'Europe',
    code: 'at',
  },
  {
    name: 'Belgium',
    activeArmedForces: 26000,
    region: 'Europe',
    code: 'be',
  },
  {
    name: 'Bosnia-Herzegovina',
    activeArmedForces: 11000,
    region: 'Europe',
    code: 'ba',
  },
  {
    name: 'Bulgaria',
    activeArmedForces: 37000,
    region: 'Europe',
    code: 'bg',
  },
  {
    name: 'Croatia',
    activeArmedForces: 15000,
    region: 'Europe',
    code: 'hr',
  },
  {
    name: 'Cyprus',
    activeArmedForces: 15000,
    region: 'Europe',
    code: 'cy',
  },
  {
    name: 'Czech Republic',
    activeArmedForces: 25000,
    region: 'Europe',
    code: 'cz',
  },
  {
    name: 'Denmark',
    activeArmedForces: 15000,
    region: 'Europe',
    code: 'dk',
  },
  {
    name: 'Estonia',
    activeArmedForces: 7000,
    region: 'Europe',
    code: 'ee',
  },
  {
    name: 'Finland',
    activeArmedForces: 24000,
    region: 'Europe',
    code: 'fi',
  },
  {
    name: 'France',
    activeArmedForces: 203000,
    region: 'Europe',
    code: 'fr',
  },
  {
    name: 'Germany',
    activeArmedForces: 184000,
    region: 'Europe',
    code: 'de',
  },
  {
    name: 'Greece',
    activeArmedForces: 143000,
    region: 'Europe',
    code: 'gr',
  },
  {
    name: 'Hungary',
    activeArmedForces: 28000,
    region: 'Europe',
    code: 'hu',
  },
  {
    name: 'Iceland',
    activeArmedForces: 0,
    region: 'Europe',
    code: 'is',
  },
  {
    name: 'Ireland',
    activeArmedForces: 9000,
    region: 'Europe',
    code: 'ie',
  },
  {
    name: 'Italy',
    activeArmedForces: 166000,
    region: 'Europe',
    code: 'it',
  },
  {
    name: 'Latvia',
    activeArmedForces: 6000,
    region: 'Europe',
    code: 'lv',
  },
  {
    name: 'Lithuania',
    activeArmedForces: 22000,
    region: 'Europe',
    code: 'lt',
  },
  {
    name: 'Luxembourg',
    activeArmedForces: 0,
    region: 'Europe',
    code: 'lu',
  },
  {
    name: 'North Macedonia',
    activeArmedForces: 8000,
    region: 'Europe',
    code: 'mk',
  },
  {
    name: 'Malta',
    activeArmedForces: 2000,
    region: 'Europe',
    code: 'mt',
  },
  {
    name: 'Montenegro',
    activeArmedForces: 2000,
    region: 'Europe',
    code: 'me',
  },
  {
    name: 'Netherlands',
    activeArmedForces: 34000,
    region: 'Europe',
    code: 'nl',
  },
  {
    name: 'Norway',
    activeArmedForces: 23000,
    region: 'Europe',
    code: 'no',
  },
  {
    name: 'Poland',
    activeArmedForces: 114000,
    region: 'Europe',
    code: 'pl',
  },
  {
    name: 'Portugal',
    activeArmedForces: 27000,
    region: 'Europe',
    code: 'pt',
  },
  {
    name: 'Romania',
    activeArmedForces: 69000,
    region: 'Europe',
    code: 'ro',
  },
  {
    name: 'Serbia',
    activeArmedForces: 28000,
    region: 'Europe',
    code: 'rs',
  },
  {
    name: 'Slovakia',
    activeArmedForces: 16000,
    region: 'Europe',
    code: 'sk',
  },
  {
    name: 'Slovenia',
    activeArmedForces: 7000,
    region: 'Europe',
    code: 'si',
  },
  {
    name: 'Spain',
    activeArmedForces: 123000,
    region: 'Europe',
    code: 'es',
  },
  {
    name: 'Sweden',
    activeArmedForces: 15000,
    region: 'Europe',
    code: 'se',
  },
  {
    name: 'Switzerland',
    activeArmedForces: 20000,
    region: 'Europe',
    code: 'ch',
  },
  {
    name: 'Turkey',
    activeArmedForces: 355000,
    region: 'Europe',
    code: 'tr',
  },
  {
    name: 'United Kingdom',
    activeArmedForces: 149000,
    region: 'Europe',
    code: 'gb',
  },
  {
    name: 'Armenia',
    activeArmedForces: 45000,
    region: 'Russia and Eurasia',
    code: 'am',
  },
  {
    name: 'Azerbaijan',
    activeArmedForces: 67000,
    region: 'Russia and Eurasia',
    code: 'az',
  },
  {
    name: 'Belarus',
    activeArmedForces: 45000,
    region: 'Russia and Eurasia',
    code: 'by',
  },
  {
    name: 'Georgia',
    activeArmedForces: 21000,
    region: 'Russia and Eurasia',
    code: 'ge',
  },
  {
    name: 'Kazakhstan',
    activeArmedForces: 39000,
    region: 'Russia and Eurasia',
    code: 'kz',
  },
  {
    name: 'Kyrgyzstan',
    activeArmedForces: 11000,
    region: 'Russia and Eurasia',
    code: 'kg',
  },
  {
    name: 'Moldova',
    activeArmedForces: 5000,
    region: 'Russia and Eurasia',
    code: 'md',
  },
  {
    name: 'Losses of russia',
    activeArmedForces: 0,
    region: 'Russia and Eurasia',
    code: '',
  },
  {
    name: 'Tajikistan',
    activeArmedForces: 9000,
    region: 'Russia and Eurasia',
    code: 'tj',
  },
  {
    name: 'Turkmenistan',
    activeArmedForces: 37000,
    region: 'Russia and Eurasia',
    code: 'tm',
  },
  {
    name: 'Ukraine',
    activeArmedForces: 209000,
    region: 'Russia and Eurasia',
    code: 'ua',
  },
  {
    name: 'Uzbekistan',
    activeArmedForces: 48000,
    region: 'Russia and Eurasia',
    code: 'uz',
  },
  {
    name: 'Afghanistan',
    activeArmedForces: 179000,
    region: 'Asia',
    code: 'af',
  },
  {
    name: 'Australia',
    activeArmedForces: 59000,
    region: 'Asia',
    code: 'au',
  },
  {
    name: 'Bangladesh',
    activeArmedForces: 163000,
    region: 'Asia',
    code: 'bd',
  },
  {
    name: 'Brunei',
    activeArmedForces: 7000,
    region: 'Asia',
    code: 'bn',
  },
  {
    name: 'Cambodia',
    activeArmedForces: 124000,
    region: 'Asia',
    code: 'kh',
  },
  {
    name: 'China',
    activeArmedForces: 2035000,
    region: 'Asia',
    code: 'cn',
  },
  {
    name: 'Fiji',
    activeArmedForces: 4000,
    region: 'Asia',
    code: 'fj',
  },
  {
    name: 'India',
    activeArmedForces: 1459000,
    region: 'Asia',
    code: 'in',
  },
  {
    name: 'Indonesia',
    activeArmedForces: 396000,
    region: 'Asia',
    code: 'id',
  },
  {
    name: 'Japan',
    activeArmedForces: 247000,
    region: 'Asia',
    code: 'jp',
  },
  {
    name: 'DPR of Korea',
    activeArmedForces: 1280000,
    region: 'Asia',
    code: 'kp',
  },
  {
    name: 'Republic of Korea',
    activeArmedForces: 599000,
    region: 'Asia',
    code: 'kr',
  },
  {
    name: 'Laos',
    activeArmedForces: 29000,
    region: 'Asia',
    code: 'la',
  },
  {
    name: 'Malaysia',
    activeArmedForces: 113000,
    region: 'Asia',
    code: 'my',
  },
  {
    name: 'Mongolia',
    activeArmedForces: 10000,
    region: 'Asia',
    code: 'mn',
  },
  {
    name: 'Myanmar',
    activeArmedForces: 406000,
    region: 'Asia',
    code: 'mm',
  },
  {
    name: 'Nepal',
    activeArmedForces: 97000,
    region: 'Asia',
    code: 'np',
  },
  {
    name: 'New Zealand',
    activeArmedForces: 9000,
    region: 'Asia',
    code: 'nz',
  },
  {
    name: 'Pakistan',
    activeArmedForces: 652000,
    region: 'Asia',
    code: 'pk',
  },
  {
    name: 'Papua New Guinea',
    activeArmedForces: 4000,
    region: 'Asia',
    code: 'pg',
  },
  {
    name: 'Philippines',
    activeArmedForces: 143000,
    region: 'Asia',
    code: 'ph',
  },
  {
    name: 'Singapore',
    activeArmedForces: 51000,
    region: 'Asia',
    code: 'sg',
  },
  {
    name: 'Sri Lanka',
    activeArmedForces: 255000,
    region: 'Asia',
    code: 'lk',
  },
  {
    name: 'Taiwan',
    activeArmedForces: 163000,
    region: 'Asia',
    code: 'tw',
  },
  {
    name: 'Thailand',
    activeArmedForces: 361000,
    region: 'Asia',
    code: 'th',
  },
  {
    name: 'Timor-Leste',
    activeArmedForces: 2000,
    region: 'Asia',
    code: 'tl',
  },
  {
    name: 'Vietnam',
    activeArmedForces: 482000,
    region: 'Asia',
    code: 'vn',
  },
  {
    name: 'Algeria',
    activeArmedForces: 130000,
    region: 'Middle East and North Africa',
    code: 'dz',
  },
  {
    name: 'Bahrain',
    activeArmedForces: 8000,
    region: 'Middle East and North Africa',
    code: 'bh',
  },
  {
    name: 'Egypt',
    activeArmedForces: 439000,
    region: 'Middle East and North Africa',
    code: 'eg',
  },
  {
    name: 'Iran',
    activeArmedForces: 610000,
    region: 'Middle East and North Africa',
    code: 'ir',
  },
  {
    name: 'Iraq',
    activeArmedForces: 193000,
    region: 'Middle East and North Africa',
    code: 'iq',
  },
  {
    name: 'Israel',
    activeArmedForces: 170000,
    region: 'Middle East and North Africa',
    code: 'il',
  },
  {
    name: 'Jordan',
    activeArmedForces: 101000,
    region: 'Middle East and North Africa',
    code: 'jo',
  },
  {
    name: 'Kuwait',
    activeArmedForces: 18000,
    region: 'Middle East and North Africa',
    code: 'kw',
  },
  {
    name: 'Lebanon',
    activeArmedForces: 60000,
    region: 'Middle East and North Africa',
    code: 'lb',
  },
  {
    name: 'Mauritania',
    activeArmedForces: 16000,
    region: 'Middle East and North Africa',
    code: 'mr',
  },
  {
    name: 'Morocco',
    activeArmedForces: 196000,
    region: 'Middle East and North Africa',
    code: 'ma',
  },
  {
    name: 'Oman',
    activeArmedForces: 43000,
    region: 'Middle East and North Africa',
    code: 'om',
  },
  {
    name: 'Qatar',
    activeArmedForces: 17000,
    region: 'Middle East and North Africa',
    code: 'qa',
  },
  {
    name: 'Saudi Arabia',
    activeArmedForces: 227000,
    region: 'Middle East and North Africa',
    code: 'sa',
  },
  {
    name: 'Syria',
    activeArmedForces: 169000,
    region: 'Middle East and North Africa',
    code: 'sy',
  },
  {
    name: 'Tunisia',
    activeArmedForces: 36000,
    region: 'Middle East and North Africa',
    code: 'tn',
  },
  {
    name: 'United Arab Emirates',
    activeArmedForces: 63000,
    region: 'Middle East and North Africa',
    code: 'ae',
  },
  {
    name: 'Yemen',
    activeArmedForces: 40000,
    region: 'Middle East and North Africa',
    code: 'ye',
  },
  {
    name: 'Antigua and Barbuda',
    activeArmedForces: 0,
    region: 'Latin America and the Caribbean',
    code: 'ag',
  },
  {
    name: 'Argentina',
    activeArmedForces: 72000,
    region: 'Latin America and the Caribbean',
    code: 'ar',
  },
  {
    name: 'Bahamas',
    activeArmedForces: 2000,
    region: 'Latin America and the Caribbean',
    code: 'bs',
  },
  {
    name: 'Barbados',
    activeArmedForces: 1000,
    region: 'Latin America and the Caribbean',
    code: 'bb',
  },
  {
    name: 'Belize',
    activeArmedForces: 2000,
    region: 'Latin America and the Caribbean',
    code: 'bz',
  },
  {
    name: 'Bolivia',
    activeArmedForces: 34000,
    region: 'Latin America and the Caribbean',
    code: 'bo',
  },
  {
    name: 'Brazil',
    activeArmedForces: 367000,
    region: 'Latin America and the Caribbean',
    code: 'br',
  },
  {
    name: 'Chile',
    activeArmedForces: 77000,
    region: 'Latin America and the Caribbean',
    code: 'cl',
  },
  {
    name: 'Colombia',
    activeArmedForces: 293000,
    region: 'Latin America and the Caribbean',
    code: 'co',
  },
  {
    name: 'Costa Rica',
    activeArmedForces: 0,
    region: 'Latin America and the Caribbean',
    code: 'cr',
  },
  {
    name: 'Cuba',
    activeArmedForces: 49000,
    region: 'Latin America and the Caribbean',
    code: 'cu',
  },
  {
    name: 'Dominican Republic',
    activeArmedForces: 56000,
    region: 'Latin America and the Caribbean',
    code: 'do',
  },
  {
    name: 'Ecuador',
    activeArmedForces: 41000,
    region: 'Latin America and the Caribbean',
    code: 'ec',
  },
  {
    name: 'El Salvador',
    activeArmedForces: 25000,
    region: 'Latin America and the Caribbean',
    code: 'sv',
  },
  {
    name: 'Guatemala',
    activeArmedForces: 18000,
    region: 'Latin America and the Caribbean',
    code: 'gt',
  },
  {
    name: 'Guyana',
    activeArmedForces: 3000,
    region: 'Latin America and the Caribbean',
    code: 'gy',
  },
  {
    name: 'Haiti',
    activeArmedForces: 1000,
    region: 'Latin America and the Caribbean',
    code: 'ht',
  },
  {
    name: 'Honduras',
    activeArmedForces: 15000,
    region: 'Latin America and the Caribbean',
    code: 'hn',
  },
  {
    name: 'Jamaica',
    activeArmedForces: 6000,
    region: 'Latin America and the Caribbean',
    code: 'jm',
  },
  {
    name: 'Mexico',
    activeArmedForces: 216000,
    region: 'Latin America and the Caribbean',
    code: 'mx',
  },
  {
    name: 'Nicaragua',
    activeArmedForces: 12000,
    region: 'Latin America and the Caribbean',
    code: 'ni',
  },
  {
    name: 'Panama',
    activeArmedForces: 0,
    region: 'Latin America and the Caribbean',
    code: 'pa',
  },
  {
    name: 'Paraguay',
    activeArmedForces: 14000,
    region: 'Latin America and the Caribbean',
    code: 'py',
  },
  {
    name: 'Peru',
    activeArmedForces: 81000,
    region: 'Latin America and the Caribbean',
    code: 'pe',
  },
  {
    name: 'Suriname',
    activeArmedForces: 2000,
    region: 'Latin America and the Caribbean',
    code: 'sr',
  },
  {
    name: 'Trinidad and Tobago',
    activeArmedForces: 5000,
    region: 'Latin America and the Caribbean',
    code: 'tt',
  },
  {
    name: 'Uruguay',
    activeArmedForces: 21000,
    region: 'Latin America and the Caribbean',
    code: 'uy',
  },
  {
    name: 'Venezuela',
    activeArmedForces: 123000,
    region: 'Latin America and the Caribbean',
    code: 've',
  },
  {
    name: 'Angola',
    activeArmedForces: 107000,
    region: 'Sub-Saharan Africa',
    code: 'ao',
  },
  {
    name: 'Benin',
    activeArmedForces: 7000,
    region: 'Sub-Saharan Africa',
    code: 'bj',
  },
  {
    name: 'Botswana',
    activeArmedForces: 9000,
    region: 'Sub-Saharan Africa',
    code: 'bw',
  },
  {
    name: 'Burkina Faso',
    activeArmedForces: 11000,
    region: 'Sub-Saharan Africa',
    code: 'bf',
  },
  {
    name: 'Burundi',
    activeArmedForces: 30000,
    region: 'Sub-Saharan Africa',
    code: 'bi',
  },
  {
    name: 'Cameroon',
    activeArmedForces: 25000,
    region: 'Sub-Saharan Africa',
    code: 'cm',
  },
  {
    name: 'Cape Verde',
    activeArmedForces: 1000,
    region: 'Sub-Saharan Africa',
    code: 'cv',
  },
  {
    name: 'Central African Republic',
    activeArmedForces: 9000,
    region: 'Sub-Saharan Africa',
    code: 'cf',
  },
  {
    name: 'Chad',
    activeArmedForces: 33000,
    region: 'Sub-Saharan Africa',
    code: 'td',
  },
  {
    name: 'Republic of the Congo',
    activeArmedForces: 10000,
    region: 'Sub-Saharan Africa',
    code: 'cg',
  },
  {
    name: "Côte d'Ivoire",
    activeArmedForces: 27000,
    region: 'Sub-Saharan Africa',
    code: 'ci',
  },
  {
    name: 'DR of the Congo',
    activeArmedForces: 134000,
    region: 'Sub-Saharan Africa',
    code: 'cd',
  },
  {
    name: 'Djibouti',
    activeArmedForces: 10000,
    region: 'Sub-Saharan Africa',
    code: 'dj',
  },
  {
    name: 'Equatorial Guinea',
    activeArmedForces: 1000,
    region: 'Sub-Saharan Africa',
    code: 'gq',
  },
  {
    name: 'Eritrea',
    activeArmedForces: 202000,
    region: 'Sub-Saharan Africa',
    code: 'er',
  },
  {
    name: 'Ethiopia',
    activeArmedForces: 138000,
    region: 'Sub-Saharan Africa',
    code: 'et',
  },
  {
    name: 'Gabon',
    activeArmedForces: 5000,
    region: 'Sub-Saharan Africa',
    code: 'ga',
  },
  {
    name: 'Gambia',
    activeArmedForces: 4000,
    region: 'Sub-Saharan Africa',
    code: 'gm',
  },
  {
    name: 'Ghana',
    activeArmedForces: 16000,
    region: 'Sub-Saharan Africa',
    code: 'gh',
  },
  {
    name: 'Guinea',
    activeArmedForces: 10000,
    region: 'Sub-Saharan Africa',
    code: 'gn',
  },
  {
    name: 'Guinea-Bissau',
    activeArmedForces: 4000,
    region: 'Sub-Saharan Africa',
    code: 'gw',
  },
  {
    name: 'Kenya',
    activeArmedForces: 24000,
    region: 'Sub-Saharan Africa',
    code: 'ke',
  },
  {
    name: 'Lesotho',
    activeArmedForces: 2000,
    region: 'Sub-Saharan Africa',
    code: 'ls',
  },
  {
    name: 'Liberia',
    activeArmedForces: 2000,
    region: 'Sub-Saharan Africa',
    code: 'lr',
  },
  {
    name: 'Madagascar',
    activeArmedForces: 14000,
    region: 'Sub-Saharan Africa',
    code: 'mg',
  },
  {
    name: 'Malawi',
    activeArmedForces: 11000,
    region: 'Sub-Saharan Africa',
    code: 'mw',
  },
  {
    name: 'Mali',
    activeArmedForces: 13000,
    region: 'Sub-Saharan Africa',
    code: 'ml',
  },
  {
    name: 'Mauritius',
    activeArmedForces: 0,
    region: 'Sub-Saharan Africa',
    code: 'mu',
  },
  {
    name: 'Mozambique',
    activeArmedForces: 11000,
    region: 'Sub-Saharan Africa',
    code: 'mz',
  },
  {
    name: 'Namibia',
    activeArmedForces: 10000,
    region: 'Sub-Saharan Africa',
    code: 'na',
  },
  {
    name: 'Niger',
    activeArmedForces: 5000,
    region: 'Sub-Saharan Africa',
    code: 'ne',
  },
  {
    name: 'Nigeria',
    activeArmedForces: 143000,
    region: 'Sub-Saharan Africa',
    code: 'ng',
  },
  {
    name: 'Rwanda',
    activeArmedForces: 33000,
    region: 'Sub-Saharan Africa',
    code: 'rw',
  },
  {
    name: 'Senegal',
    activeArmedForces: 14000,
    region: 'Sub-Saharan Africa',
    code: 'sn',
  },
  {
    name: 'Seychelles',
    activeArmedForces: 0,
    region: 'Sub-Saharan Africa',
    code: 'sc',
  },
  {
    name: 'Sierra Leone',
    activeArmedForces: 9000,
    region: 'Sub-Saharan Africa',
    code: 'sl',
  },
  {
    name: 'Somalia',
    activeArmedForces: 20000,
    region: 'Sub-Saharan Africa',
    code: 'so',
  },
  {
    name: 'South Africa',
    activeArmedForces: 75000,
    region: 'Sub-Saharan Africa',
    code: 'za',
  },
  {
    name: 'South Sudan',
    activeArmedForces: 185000,
    region: 'Sub-Saharan Africa',
    code: 'ss',
  },
  {
    name: 'Sudan',
    activeArmedForces: 104000,
    region: 'Sub-Saharan Africa',
    code: 'sd',
  },
  {
    name: 'Tanzania',
    activeArmedForces: 27000,
    region: 'Sub-Saharan Africa',
    code: 'tz',
  },
  {
    name: 'Togo',
    activeArmedForces: 9000,
    region: 'Sub-Saharan Africa',
    code: 'tg',
  },
  {
    name: 'Uganda',
    activeArmedForces: 45000,
    region: 'Sub-Saharan Africa',
    code: 'ug',
  },
  {
    name: 'Zambia',
    activeArmedForces: 15000,
    region: 'Sub-Saharan Africa',
    code: 'zm',
  },
  {
    name: 'Zimbabwe',
    activeArmedForces: 29000,
    region: 'Sub-Saharan Africa',
    code: 'zw',
  },
];
